### ISSUE TITLE
Cupy: cudaErrorIllegalAddress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by janbechtold** [hoshino042/bilateral_normal_integration#1]
Hi,
thanks for your great work. I run into the above mentioned cuda error when running the cupy script on the following normal map. 
I was wondering whether you can reproduce the issue and have an idea where to start looking. Potentially somewhere where the masks are computed or the diagonal_data_term is updated.

It works with the numpy script, but I want to use the cupy script as it is faster for many of my normal_maps.

Looking forward to hearing from you.
Best,
Jan

[K.txt](https://github.com/hoshino042/bilateral_normal_integration/files/10427630/K.txt)

![mask](https://user-images.githubusercontent.com/22617469/212724141-2b9b3aca-7bdc-450e-a979-2ec7a30454d6.png)
![normal_map](https://user-images.githubusercontent.com/22617469/212724168-6a9d8996-dbfd-4a67-bfb8-28ca42abfb5b.png)

**Comment by hoshino042** [comment]
Hi, I have tried running the cupy script on your data, but I did not encounter any issue. I tested using cuda 11.3 with cupy-cuda11x.

I guess the possible reasons for this cuda error are due to the conflict with other threads using cuda (e.g., pytorch) or parallelization running.
Have you tried running the script along?

Hope it helps.

**Comment by janbechtold** [comment]
Hi,
thanks for your quick response and testing it on my data.
For me the error is reproducible for a number of shapes. I could not figure out yet what they have in common. Independent of the time or machine that I run on. Also there are no other GPU processes running when I start the script.

These are my cuda, cupy versions:
- cuda/10.2.89
- cudnn/10.2_v7.6
- cupy-cuda102 (name)             11.3.0 (version)

So I'll try with a newer cuda version. Thanks for the hint.

**Comment by janbechtold** [comment]
I updated my environment to use cuda/11.3 and respectively cupy-cuda11x (name) 11.4.0 (version)

Additional remark: I had to update pyvista to 0.37.0 to resolve another error 
(ImportError: cannot import name 'vtkExtractEdges' from 'vtkmodules.vtkFiltersExtraction')

This resolves my issue. Thanks again for the hint.
